spring:
  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true